# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DLNA_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DLNA_Demo
  pod 'CocoaAsyncSocket'
  pod 'GCDWebServer', "~> 3.0"
  pod 'GCDWebServer/WebDAV', "~> 3.0"
  
  #用于网络出错 提示
  pod 'SVProgressHUD'
end
